spring.application.name=scaffold

spring.datasource.url=jdbc:mysql://localhost:3306/shrooms_scaffold?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Niki2901

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true